language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: ci@radon.app
  api_key:
    secure: sAspiF/dH0Rj4YIHct68errTMlYgqcYG4vKsQf6X6Eu3+ZhC3wjoUeg5Uc6ZohsEYo8plVnhhZ5//UMY2hGxv308L1Ag/YQpdC/37QPCEIoGxexWWj6XAkPammawe9xs15c7mW+furkYVFAulCei0bRLYlntgWcRuvUAA4V6i6jnybtmKuWcgmd5VtyvWJdBh71tPmy0sq1UKsr0hCKnm58navyOU5nYy5oQM3iOSwq95CHg6dYDDwpBpBcSyx9OELzQUUuwlSh+tL0CNgJ+QJuhbcaBV5aCk+cRHDgP9Fv501tzPHjdHK/ncmg3d63+udZP+OLNfFHGk1QqO/bR9vaxWJXAqGba1YirBWVLQdVGOGXKQOZbkFU+ZJpnnsFwF07ssE45bUrktQZag4MOcLNG2cxvpaWjG59oe2B3aWyBtKz9gcHO8HKt/VOl6TIHX+9YGOIVdjQBkGd6iZjyxFbu1ceZXGvcgn/LZ7ZU2Bg6mzpNDgx8CUh24Qf4Ayzwxidz7XxAZuqFB+WTJzs3LkEdYNydaWzXzC2AD0xEe0jVn3RM+qtBaySIKO1K4dRknhgtKL8ock8ahRNd8lZeGVKXGDSWaIdplHtYVJQNuRkNoxs0/lD8meTFKltmEKJhGJCNrODoeHedJOgAythrx7tOZzK9qH2iAmWg3K3Tfgk=
  on:
    tags: true
    repo: RadonApp/radon-extension-core
